### ISSUE TITLE
Include DataUriSvgWriter?

### ISSUE THREAD

**Issue by ThomasLandauer** [endroid/QrCode#101]
Is there a specific reason why the Twig function `qrcode_data_uri()` cannot generate SVG? Implemenation looks straightforward to me: Just create `DataUriSvgWriter` (extending `SvgWriter`, as `DataUriWriter` does). Can I commit that?

**Comment by endroid** [comment]
Hi @ThomasLandauer no problem. Feature requests are always welcome. I added a SvgDataUriWriter in 2.0.6 and extended the qrcode_data_uri method so it works like the qrcode_path method.

**Comment by ThomasLandauer** [comment]
Wow, cool! :-)

However, there's an issue which I don't know how to fix: The Twig extension is effectively calling `SvgWriter`, not `SvgDataUriWriter`! Result: The `data:image/svg+xml;base64,` part is missing from the output.

**Comment by endroid** [comment]
I already noticed. This should be fixed in the latest version.

**Comment by ThomasLandauer** [comment]
Well, I'm having trouble keeping up with `composer update` today.... ;-)  
Thanks, works now!
