### ISSUE TITLE
QrCode output problem

### ISSUE THREAD

**Issue by acvoliveira** [endroid/QrCode#104]
Hi, I've just installed endroid/QrCode using composer, and used the following script to generate a QR Code.
`<?php
    require_once 'vendor/autoload.php';
    use Endroid\QrCode\ErrorCorrectionLevel;
    use Endroid\QrCode\LabelAlignment;
    use Endroid\QrCode\QrCode;
    use Endroid\QrCode\Writer\PngWriter;
    use Endroid\QrCode\Writer\SvgWriter;
    use Symfony\Component\HttpFoundation\Response;
    $qrcode = new QrCode('www.uol.com.br');
    //$qrcode -> setText();
    $qrcode -> setSize(200)
            ->setMargin(10)
            ->setEncoding('UTF-8')
            ->setErrorCorrectionLevel(ErrorCorrectionLevel::HIGH)
            ->setForegroundColor(['r' => 0, 'g' => 0, 'b' => 0])
            ->setBackgroundColor(['r' => 255, 'g' => 255, 'b' => 255])
            ->setLogoSize(150)
            ->setValidateResult(true)
    ;
            header('Content-Type: '. $qrcode->getContentType(PngWriter::class));
            $qrcode->writeString(PngWriter::class);
 ?>`

But there is no output.  The webpage is blank.  What i'm I doing wrong?

Follow the version of the QRCode I'm using

alexandres-mbp:QRCODE AlexHD$ composer show
Cannot create cache directory /Users/AlexHD/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /Users/AlexHD/.composer/cache/files/, or directory is not writable. Proceeding without cache
Cannot create cache directory /Users/AlexHD/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
bacon/bacon-qr-code                 1.0.1   BaconQrCode is a QR code genera...
endroid/qrcode                      2.1.4   Endroid QR Code
khanamiryan/qrcode-detector-decoder 0.0.1   QR code decoder / reader
myclabs/php-enum                    1.5.1   PHP Enum implementation
paragonie/random_compat             v2.0.10 PHP 5.x polyfill for random_byt...
symfony/inflector                   v3.2.8  Symfony Inflector Component
symfony/options-resolver            v3.2.8  Symfony OptionsResolver Component
symfony/polyfill-php70              v1.3.0  Symfony polyfill backporting so...
symfony/property-access             v3.2.8  Symfony PropertyAccess Component
alexandres-mbp:QRCODE AlexHD$ 

PHP version
alexandres-mbp:QRCODE AlexHD$ php -v
PHP 7.1.2 (cli) (built: Mar 10 2017 23:34:38) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.1, Copyright (c) 2002-2017, by Derick Rethans
alexandres-mbp:QRCODE AlexHD$

**Comment by endroid** [comment]
Hi @acvoliveira you still need to echo the string created by the writeString method (if you look closer at the code you can see that the writeString returns a string and does not output anything).

**Comment by mostafa619** [comment]
hi,i was generating my QR codes but after uploading my website to a host and try to generate my qr code there is no output. The web page is blank. What i'm I doing wrong? that is the code
<?php
ob_start();
include 'Connection.php';
require_once('vendor/autoload.php');
use Endroid\QrCode\QrCode;
//variables:-
$ccode=$_POST['ccode'];
$qr=$_POST['text'];
$lecnum=$_POST['qr'];
//check if lecutr_number exist:-
$stmt=$con->prepare("SELECT lecture_number from lecture_qrcode WHERE course_code=? and lecture_number like ?");
$stmt->execute(array($ccode,$lecnum));
$count=$stmt->rowCount();
if($count>=1){
echo'Please change lecutre_number';
goto leave;
}
//check if qrcode is exist:-
$stmt=$con->prepare("SELECT qrcode from lecture_qrcode WHERE  qrcode=? ");
$stmt->execute(array($qr));
$count1=$stmt->rowCount();
if($count1>=1){
echo 'Sorry,but please change the qrcode';
goto leave;
}
else{
//create qrcode and insert it into the database
$stmt=$con->prepare("INSERT INTO lecture_qrcode values(?,?,?)");
$stmt->execute(array($lecnum,$qr,$ccode));
$qrCode = new QrCode($_POST['text']);
header("Content-Type: image/png");
echo $qrCode->writeString();
die();
}
ob_end_flush();
leave:
?>

**Comment by endroid** [comment]
Hi @mostafa619 you could try to debug step by step and verify your script is working. Also it helps if you comment the header("Content-Type: image/png"); so your browser does not try to render any errors as an image. Good luck!

**Comment by mostafa619** [comment]
thank you

**Comment by AsadbekDevUZB** [comment]
Hi. I've a problem. Uncaught Exception: Invalid data at path "C:\OpenServer\domains\smalot_pdf_parser/assets/symfony.png" in C:\OpenServer\domains\smalot_pdf_parser\vendor\endroid\qr-code\src\ImageData\LogoImageData.php:

**Comment by mohammedidris11** [comment]
hello endroid ,,, I have problem when run the code after install library I will show blank page in the web browser. the code is below :
<?php

use Endroid\QrCode\Color\Color;
use Endroid\QrCode\Encoding\Encoding;
use Endroid\QrCode\ErrorCorrectionLevel\ErrorCorrectionLevelLow;
use Endroid\QrCode\QrCode;
use Endroid\QrCode\Label\Label;
use Endroid\QrCode\Logo\Logo;
use Endroid\QrCode\RoundBlockSizeMode\RoundBlockSizeModeMargin;
use Endroid\QrCode\Writer\PngWriter;
use Endroid\QrCode\Writer\ValidationException;

$writer = new PngWriter();

// Create QR code
$qrCode = QrCode::create('Life is too short to be generating QR codes')
    ->setEncoding(new Encoding('UTF-8'))
    ->setErrorCorrectionLevel(new ErrorCorrectionLevelLow())
    ->setSize(300)
    ->setMargin(10)
    ->setRoundBlockSizeMode(new RoundBlockSizeModeMargin())
    ->setForegroundColor(new Color(0, 0, 0))
    ->setBackgroundColor(new Color(255, 255, 255));

// Create generic logo
$logo = Logo::create(__DIR__.'/assets/symfony.png')
    ->setResizeToWidth(50);

// Create generic label
$label = Label::create('Label')
    ->setTextColor(new Color(255, 0, 0));

$result = $writer->write($qrCode, $logo, $label);

// Validate the result
$writer->validateResult($result, 'Life is too short to be generating QR codes');







// Directly output the QR code
header('Content-Type:image/png'.$result->getMimeType());
echo $result->getString();

// Save it to a file
$result->saveToFile(__DIR__.'/qrcode.png');

// Generate a data URI to include image data inline (i.e. inside an <img> tag)
$dataUri = $result->getDataUri();
?>

**Comment by endroid** [comment]
Hi @mohammedidris11 I see you save the result to a file so you should either see the file in your file system or have an error. You could try to remove the image header so you can see the error message in your browser or change your error reporting level etc to make sure you see errors. Good luck!

**Comment by akayves** [comment]
hi, when i try to generate qr-code with your tutorial on youtube, i get an error. this is error Uncaught Exception: Invalid data at path "/path/to/the/logo/file

**Comment by vane24ofc** [comment]
Hola, ejecuto el codigo para la generacion de los qr: <?php
// Asegurar que Composer ha sido cargado
require_once __DIR__ . '/../vendor/autoload.php';

use Endroid\QrCode\QrCode;
use Endroid\QrCode\Writer\PngWriter;
use Endroid\QrCode\ErrorCorrectionLevel;

// Configuración de la base de datos
$host = "127.0.0.1";
$usuario = "root";
$contraseña = "";
$base_datos = "qr_system";

// Conectar a la base de datos
$conn = new mysqli($host, $usuario, $contraseña, $base_datos);
if ($conn->connect_error) {
    die("Error de conexión: " . $conn->connect_error);
}

// Datos del usuario
$nombre = "Usuario Test";
$email = "usuario@example.com";
$rol = "empleado";
$codigo = uniqid('qr_', true);  // Uso de 'qr_' como prefijo para mayor claridad
$fecha_expiracion = date('Y-m-d H:i:s', strtotime('+2 minutes')); // Expira en 2 minutos

// Directorio donde se guardarán los QR
$dir = __DIR__ . "/../qrcodes/";
if (!file_exists($dir)) {
    mkdir($dir, 0777, true);
}

// Crear el código QR directamente usando QrCode
$qrCode = new QrCode("Nombre: $nombre\nEmail: $email\nRol: $rol\nCódigo: $codigo\nExpira: $fecha_expiracion");

// Establecer propiedades del QR
$qrCode->setErrorCorrectionLevel(ErrorCorrectionLevel::HIGH)
       ->setSize(300)
       ->setMargin(10);

// Guardar el QR generado
$qr_filename = $dir . $codigo . '.png';
$writer = new PngWriter();
$writer->writeFile($qrCode, $qr_filename);

// **Escapar datos para evitar inyección SQL**
$nombre = $conn->real_escape_string($nombre);
$email = $conn->real_escape_string($email);
$rol = $conn->real_escape_string($rol);
$qr_filename = $conn->real_escape_string($qr_filename);
$fecha_expiracion = $conn->real_escape_string($fecha_expiracion);

// Insertar en la base de datos
$sql = "INSERT INTO usuarios (nombre, email, rol, codigo_qr, qr_expiracion) 
        VALUES ('$nombre', '$email', '$rol', '$qr_filename', '$fecha_expiracion')";

if ($conn->query($sql) === TRUE) {
    echo "✅ Código QR generado correctamente: <br>";
    echo "<img src='/qrcodes/$codigo.png' />";  // Ajuste de la ruta para ser relativa al servidor
    echo "<br><a href='/qrcodes/$codigo.png' download>📥 Descargar QR</a>";
} else {
    echo "❌ Error al guardar en la base de datos: " . $conn->error;
}

// Cerrar conexión
$conn->close();
?>
 y aparece esto: Fatal error: Uncaught Error: Call to undefined method Endroid\QrCode\QrCode::setErrorCorrectionLevel() in C:\xampp\htdocs\Autenticacion_qr\php\generar_qr.php:38 Stack trace: #0 {main} thrown in C:\xampp\htdocs\Autenticacion_qr\php\generar_qr.php on line 38
