### ISSUE TITLE
install error,  file could not be downloaded 

### ISSUE THREAD

**Issue by grekpg** [endroid/QrCode#105]
"endroid/qrcode-bundle": "^1.6",

Loading composer repositories with package information                                                                                                                         Updating dependencies (including require-dev)           - Installing endroid/qrcode-bundle (1.6.6)
    Downloading: Failed       
    Failed to download endroid/qrcode-bundle from dist: The "https://api.github.com/repos/endroid/EndroidQrCodeBundle/zipball/f8f12fd9f6414a98e21b85acac4859d40b70130e" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
Permission denied (publickey).

**Comment by endroid** [comment]
Hi @grekpg you can install "endroid/qrcode" and use the bundle you can find there. The qrcode-bundle package has been abandoned for about a half year and removed about a week ago.
