### ISSUE TITLE
setMargin not working

### ISSUE THREAD

**Issue by anujsharma9196** [endroid/QrCode#106]
I'm using version 2.0.9

while setting margin by using 
```
$qrCode
   ->setMargin(10);
```

It gives error as  **_Call to undefined method Endroid\QrCode\QrCode::setMargin()_** 

> **Suggestion**
> Please add current version number of the package to that one could compare it with version installed.

**Comment by endroid** [comment]
Hi, that method was added recently so upgrading to the latest version should solve your issue.

**Comment by anujsharma9196** [comment]
Which version is the latest?
running `composer update endroid/qrcode` only installs **2.0.9**

**Comment by endroid** [comment]
You can always find the latest release(s) here:
https://github.com/endroid/QrCode/releases
https://packagist.org/packages/endroid/qrcode

If Composer does not install the latest version on update there are probably some requirements in the newer versions that conflict with your project requirements.
