### ISSUE TITLE
When install imagick extension, how to deal with reporting error "Unknown pixel type" in file IMagickLuminanceSource.php line 6

### ISSUE THREAD

**Issue by yolanda616** [endroid/QrCode#110]
when installing imagick extension, \Imagick::COLORSPACE_RGB value is 21, so that reporting error "Unknown pixel type" in file IMagickLuminanceSource.php line 64.

However, when using phpstorm open file  IMagickLuminanceSource.php line 64 ,jump to implementations of \Imagick::COLORSPACE_RGB, the value is 1.

Sulotion: modify \Imagick::COLORSPACE_RGB with \Imagick::PIXEL_CHAR,

**Comment by endroid** [comment]
Hi @yolanda616, thank you. I see that code is part of the https://github.com/khanamiryan/php-qrcode-detector-decoder library which I don't maintain. Please create an issue there so the package maintainer can look at it.
