### ISSUE TITLE
Error in TWIG in Symfony

### ISSUE THREAD

**Issue by MicWit** [endroid/QrCode#111]
I am trying to put a QR Code into a TWIG template in Symfony. The controller works out the URL and should feed it into the bundle in Symfony. As a basic test in twig, I hard coded a url:
`<img src="{{ qrcode_url('http://www.test.com') }}" />`
and when this is run, get the message:

> An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "endroid_qrcode_generate" as such route does not exist.").

I am using Symfony 3.3.2 and TWIG 1.34.3.

Not sure if I am doing something wrong as there are no real life examples anywhere I can find (just the few lines under TWIG in the readme). I installed the bundle via composer and added it to AppKernel as the docs said.

**Comment by endroid** [comment]
Hi @MicWit, the documenation regarding the Twig methods is short indeed as there is nothing more to it. The syntax looks good but the exception indicates the route is missing. Did you configure the route as described in the readme? Something like this should make the routes available to your application.

EndroidQrCodeBundle:
    resource: "@EndroidQrCodeBundle/Controller/"
    type:     annotation
    prefix:   /qrcode

The following command will output all route names with "qrcode" in it.
bin/console debug:router | grep qrcode
