### ISSUE TITLE
Breaking Change: Twig Extension qrcode_url

### ISSUE THREAD

**Issue by moroine** [endroid/QrCode#113]
The following code was working on v2.1.4 but no more in v2.2.3

`<img src="{{ qrcode_url(qrcodes[device.id], {extension:'png', size:300} ) }}"/>`

**Comment by moroine** [comment]
Got the following error: `An exception has been thrown during the rendering of a template ("The option "extension" does not exist. Defined options are: "background_color", "encoding", "error_correction_level", "foreground_color", "label", "label_alignment", "label_font_path", "label_font_size", "label_margin", "logo_path", "logo_width", "margin", "size", "validate_result", "writer".").`

**Comment by endroid** [comment]
Hi @moroine this was a BC break introduced in a later version indeed. In this version you can use the "writer" parameter like described in the readme.

**Comment by moroine** [comment]
I double checked on my previous composer.lock on which my project was working properly with the version v2.1.4 

Moreover the v2.1.4 README version specify to use extension and not writer ! 

It's not a big deal, I already manage to update my project to use the `writer` option instead.

**Comment by endroid** [comment]
Good to hear you solved it. Sorry for the inconvenience, I try to keep BC breaking changes to a minimum.
