### ISSUE TITLE
Generated label with logo cannot be read

### ISSUE THREAD

**Issue by acosonic** [endroid/QrCode#115]
Even if I take your sample code, it does not work...

But it does work when logo is removed...

![works](https://user-images.githubusercontent.com/862015/27582135-32ce45fe-5b30-11e7-93b2-749fea7012c8.png)
![does_not_work](https://user-images.githubusercontent.com/862015/27582139-346190a6-5b30-11e7-9245-87865e52adfa.png)

**Comment by endroid** [comment]
Thank you for noticing. I updated the example so it creates a valid QR code.

FYI: you can always change parameters like the error correction level, image size or logo size to make an image more readable and use the built-in validator if you want to guarantee a certain minimum level of readability.
