### ISSUE TITLE
"myclabs/php-enum" in composer.json

### ISSUE THREAD

**Issue by pgrzelka** [endroid/QrCode#116]
There is no entry for "myclabs/php-enum" in composer.json so I get errors like: 
>  'Class 'MyCLabs\Enum\Enum' not found'

**Comment by endroid** [comment]
Hi @pgrzelka this issue was resolved a month ago, see https://github.com/endroid/QrCode/commit/1b981b00a925db9cbdabf5b5af3335d1f26ae178. Please install the latest version.
