### ISSUE TITLE
How can I check if the qrcode image is generated or not

### ISSUE THREAD

**Issue by puneetdevs** [endroid/QrCode#117]
`$displayValue= 'QR Data here';`
`$qrCode = new QrCode($displayValue);`
	`$qrCode->setSize(150);`
	`$qrCode
	    ->setWriterByName('png')
	    ->setMargin(10)
	    ->setEncoding('UTF-8')
	    ->setErrorCorrectionLevel(ErrorCorrectionLevel::LOW)	    
	    ->setValidateResult(false);`
   `$filename = 'path/to/folder/qrimage-'.md5($displayValue).'.png';`
	`$qrCode->writeFile($filename);`
	`return basename($filename);`

I am trying to get the name of the image, but writeFile() not able write the image, but working on XAMP localhost.

**Comment by endroid** [comment]
Hi @puneetdevs if you want to check if the QR code image is generated just output the $filename variable (you can also do this before the writeLine call) and see if a file with that name is created in that folder after the writeLine method is executed. If no file is created or your script breaks without returning an error or any output you might want to check your error reporting settings and see if the path you are writing to has write access. Maybe this post helps: https://stackoverflow.com/questions/1053424/how-do-i-get-php-errors-to-display.

As debugging or checking if a file is written is a general PHP beginners question and not specifically related to this library I will close this issue but feel free to ask if you have further questions.
