### ISSUE TITLE
Smaller dots with few data

### ISSUE THREAD

**Issue by toleabivol** [endroid/QrCode#119]
Hello , 
is it possible to get smaller dots/squares when encoding few data like "1234567891011" ?
I mean , when encoding the number above I get big squares and few dots (that makes sense as there are only a few numbers). Then I add dummy data to this number to get it prettier (smaller squares). Can this be done without dummy data addition ?

**Comment by endroid** [comment]
Hi @toleabivol, unfortunately currently there is no other way to achieve this as there is no real way to set the output block width. At least for PNG. You could however take the SVG output and write a post processor that modifies the block widths.
