### ISSUE TITLE
Update dependency for khanamiryan/qrcode-detector-decoder

### ISSUE THREAD

**Issue by ThomasLandauer** [endroid/QrCode#120]
It looks like that package released a new major version, and also changed its name: https://github.com/khanamiryan/php-qrcode-detector-decoder

You're still requiring:
```
khanamiryan/qrcode-detector-decoder 0.0.1
```

**Comment by endroid** [comment]
Hi @ThomasLandauer there is a new version but I did not update it yet as no code was changed (only unit tests added). Now I updated my composer.json to use any version on the 1.x branch for future compatibility. The package name was not changed, maybe you're confusing it with the repository name.

Thank you!

**Comment by ThomasLandauer** [comment]
:-)
