### ISSUE TITLE
Breaking change

### ISSUE THREAD

**Issue by moroine** [endroid/QrCode#122]
Hi,

I've update from 2.2.4 to 2.3.1. My Kernel.php is now broken due to moving from 
`Endroid\QrCode\Bundle\EndroidQrCodeBundle` to `Endroid\QrCode\Bundle\QrCodeBundle\EndroidQrCodeBundle` in that commit: https://github.com/endroid/QrCode/commit/8e14e3083660278e96188f233cef4cf880f6b31d#diff-bbb06a9d336e307e07801a3871f0869e

Thanks,

**Comment by endroid** [comment]
Hi @moroine that is right. The namespace changed in a recent version. It should work again when you update the namespace in your kernel. If it doesn't please let me know.

**Comment by moroine** [comment]
Yeap it does, but this is not compliant with the Sermver

**Comment by endroid** [comment]
Good to hear you were able to fix it. I keep BC breaking changes to a minimum but they can occur so always make sure you test your code when upgrading.

Thank you for your input!
