### ISSUE TITLE
Installation Issue.

### ISSUE THREAD

**Issue by chchar74** [endroid/QrCode#123]
Hi All,

Need help to install QrCode under Win 10/Apache/PHP. The following is the method:

1. Download QrCode-master.zip
2. Unzip and saved into  C:\Apache24\htdocs\QrCode
3. From Command prompt, I received following error message :

C:\Apache24\htdocs\QrCode>composer require endroid/qrcode
Using version ^2.3 for endroid/qrcode
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package endroid/qrcode No version set (parsed as 1.0.0) is satisfiable by endroid/qrcode[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by chchar74** [comment]
When I run my sample code from browser and facing following error : 

<?php

use Endroid\QrCode\QrCode;

$qrCode = new QrCode();
$qrCode->setText('http://ourcodeworld.com')
    ->setSize(300)
    ->setPadding(10)
    ->setErrorCorrection('high')
    ->setForegroundColor(array('r' => 0, 'g' => 0, 'b' => 0, 'a' => 0))
    ->setBackgroundColor(array('r' => 255, 'g' => 255, 'b' => 255, 'a' => 0))
    // Path to your logo with transparency
    ->setLogo("logo.png")
    // Set the size of your logo, default is 48
    ->setLogoSize(98)
    ->setImageType(QrCode::IMAGE_TYPE_PNG)
;

// Send output of the QRCode directly
header('Content-Type: '.$qrCode->getContentType());
$qrCode->render();

?>

Error
----- 
( ! ) Fatal error: Class 'Endroid\QrCode\QrCode' not found in C:\Apache24\htdocs\QrCode\getCode.php on line 5
--

**Comment by endroid** [comment]
Hi @chchar74 it looks like you did not include the autoloader created by Composer. See https://getcomposer.org/doc/01-basic-usage.md#autoloading for more information on how to do this.
