### ISSUE TITLE
QrCode Works only on Localhost

### ISSUE THREAD

**Issue by oluwatayo** [endroid/QrCode#124]
I recently uploaded  a project to an online server. The QrCode worked perfectly on localhost, but shows noting on the online server

**Comment by endroid** [comment]
Hi @oluwatayo this could be anything as I don't know anything about your set-up. Make sure you enable error reporting and display errors, check the server log or simply put a die('bladiebla') at the very beginning of your script to make sure your script is even executed.

**Comment by vicentepcamargo** [comment]
I'm having the same issue on my project!!

I'm using CodeIgniter and having this error:

![526eb3b27ded1b20c3104c52d7404c83](https://user-images.githubusercontent.com/50962056/67046822-6569ac00-f107-11e9-81ae-2440bf647c9e.png)

**Comment by endroid** [comment]
Hi @vicentepcamargo please check your server logs or let PHP display your errors and provide the exact PHP error message. A generic browser 500 error does not give any information on what went wrong :)
