### ISSUE TITLE
The qrcode generated is problematic in this case

### ISSUE THREAD

**Issue by emanci** [endroid/QrCode#129]
The qrcode generated is problematic in this case, scan the qrcode without any response
```php
<?php
$url = http://www.baidu.com/?code=abcxxxxabc&name=yiming&source=tt
$qrCode = new QrCode($url);
$qrCode->setSize(300);
// Set advanced options
$qrCode
    ->setWriterByName('png')
    ->setMargin(10)
    ->setEncoding('UTF-8')
    ->setErrorCorrectionLevel(ErrorCorrectionLevel::HIGH)
    ->setForegroundColor(['r' => 0, 'g' => 0, 'b' => 0])
    ->setBackgroundColor(['r' => 255, 'g' => 255, 'b' => 255]);

header('Content-Type: '.$qrCode->getContentType());
echo $qrCode->writeString();
```
You might try it, thanks!

**Comment by endroid** [comment]
Hi @emanci I have the same issue when I generate the code. This appears to be an issue in an internal library. I added your example in the corresponding thread and you can track progress there https://github.com/Bacon/BaconQrCode/issues/28.

**Comment by emanci** [comment]
@endroid I see.Thank you!
