### ISSUE TITLE
 Call to undefined function BaconQrCode\Encoder\iconv() 

### ISSUE THREAD

**Issue by AdnanHussainTurki** [endroid/QrCode#130]
Getting this for qrcode of more than 1 character
Fatal error: Uncaught Error: Call to undefined function BaconQrCode\Encoder\iconv() in /home/--------/public_html/sub/qrcode/vendor/bacon/bacon-qr-code/src/BaconQrCode/Encoder/Encoder.php:627 

Iconv | Rui Hirokawa, Stig Bakken, Moriyoshi Koizumi 
is in my PHP installation

Although It works fine on local machine

**Comment by stempora** [comment]
You need to install iconv on the server. I just encountered the same error. Look in phpinfo if you have a special section with iconv, its not enough to have --with-iconv
