### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by lem356** [endroid/QrCode#131]
Hi,
I'm getting the following message trying to install:
C:\Apache24\htdocs\QrCode>composer require endroid/qrcode
Using version ^2.3 for endroid/qrcode
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- The requested package endroid/qrcode No version set (parsed as 1.0.0) is satisfiable by endroid/qrcode[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

How can solve IT?
Thank you very much in advance,

**Comment by endroid** [comment]
Hi @lem356 you could try to add the library manually and run composer update endroid/qrcode or run the following commands in a clean directory.

composer init
composer require endroid/qrcode

Other users don't seem to have the issue and I have made no changes recently, so it seems like there is an issue with your environment or installation.
