### ISSUE TITLE
How to set the gap distance between logo and qrcode content

### ISSUE THREAD

**Issue by KeepChen** [endroid/QrCode#134]
Please tell me how to set the gap distance between logo and qrcode content?

**Comment by endroid** [comment]
Hi @KeepChen I don't know what you need this for, but maybe it is good to know that the logo is always centered and there is no way to give it an absolute position. This means that if you want the logo to be placed at position X you have to make sure you set the logo width to (qr code width - 2X).

**Comment by KeepChen** [comment]
@endroid  Thanks a lot!
