### ISSUE TITLE
Please use semantic versioning

### ISSUE THREAD

**Issue by Sander-Toonen** [endroid/QrCode#136]
The latest release (2.4.0) introduced a BC-break. Although the break was clearly mentioned on the release page not all people will look there on every minor update and there will be people running into problems when they use "^2.0" as a composer constraint for this package. 

The reason to use the "^2.0" constraint as opposed to ">=2.0.0" is that people assume 2.x.y releases to be backwards compatible. Composer will update packages up until version 3.0.0 at which point users can investigate which changes are necessary in order to update to the next major version. 

Please see http://semver.org/ for more information. Using semantic versioning helps people trusting your packages since you thereby pledge not to break existing installations with minor updates.

So I guess my question is, would you please update the major version number on the next BC-break? Thank you!

**Comment by endroid** [comment]
Hi @Sander-Toonen thank you for your input. I know semver and its rules but for a smaller BC breaking change like this I choose to do a smaller upgrade and mention the break in the commit. In case of larger refactorings or when I build a new version I bump the major version.

In other words I try to put all BC breaking changes in one new major release and keep BC breaks to a minimum within a major version but I do not always blindly follow semver.
