### ISSUE TITLE
tag please

### ISSUE THREAD

**Issue by cordoval** [endroid/QrCode#140]
symfony 4 is out and your last commit on master introduces several fixes for this

endroid/qrcode 2.4.0 requires symfony/property-access ^2.7|^3.0 -

can you please tag 2.5 ?

**Comment by endroid** [comment]
Hi @cordoval I now tagged the latest version in the 2.x branch 2.5.0. Currently I am doing a major refactoring in the master (3.x) branch so I will not tag that version yet.
