### ISSUE TITLE
Making the routing/controller part optional

### ISSUE THREAD

**Issue by iltar** [endroid/QrCode#142]
Currently when you're using this package + the bundle, you're forced to register the controllers. I do not need nor want those controllers in my application, but I have to register the router config in order to use the twig extension.

My proposal is to split the `QrCodeExtension` into 2 classes:
 - QrCodeRoutingExtension (qrCodePathFunction, qrCodeUrlFunction)
 - QrCodeUriExtension (qrCodePathFunction, qrCodeUrlFunction)

For BC purposes, the QrCodeExtension could be simply made deprecated while the bundle configures the right ones depending on your config.

**Comment by endroid** [comment]
I agree as the methods indeed serve very different purposes. Would be a good optimization. If you want to create a PR for this I'd be happy to merge.
