### ISSUE TITLE
SVG output

### ISSUE THREAD

**Issue by hyjk2000** [endroid/QrCode#24]
Vector formats are useful for QR Codes. Given the popularity and browser support of SVG, I think many people would like to have SVG output in this project.

**Comment by endroid** [comment]
I agree, this would be a useful feature. Hope anyone is willing to contribute on this.

**Comment by lahdekorpi** [comment]
I'm guessing this ain't happening?

**Comment by endroid** [comment]
Not unless someone is willing to contribute on this feature.

**Comment by endroid** [comment]
Looks like the new core library used in 2.x supports this feature. Please try it and let me know if this works for you. Please note that documentation of 2.x is not yet up to date and some features like adding a logo or a label still need to be ported to this new version.

**Comment by Emilio-Staropoli** [comment]
Doesn't work for me, I'm trying 
`writeString(SvgWriter::class)`
but I always get a png image. Tried playing around a bit (with MIME type etc) but to no avail :(

**Comment by simondowdles** [comment]
@Emilio-Staropoli 

The SVG works perfectly. Here is how I used it:

` $qrCode = new QrCode( get_site_url() . '/some/path/to/api/' );
            $qrCode
                ->setMargin(10)
                ->setEncoding('UTF-8')
                ->setErrorCorrectionLevel( ErrorCorrectionLevel::HIGH )
                ->setBackgroundColor( [ 'r' => 255, 'g' => 255, 'b' => 255 ] )
                ->setForegroundColor( [ 'r' => 0, 'g' => 0, 'b' => 0 ] )
                ->setLabel( 'Test', 12, SD_PATH . 'vendor/endroid/qrcode/assets/noto_sans.otf', LabelAlignment::CENTER, [ 'b' => 20 ] )
                ->setLogoPath( SD_PATH . 'assets/img/eye.png')
                ->setLogoWidth( 150 )
                ->setSize(200)
                ->setWriterByName('png');
            
            $svg = new SvgWriter();
            
            echo $svg->writeString( $qrCode ) ;`

It's important that you pass your original QrCode class item back to SvgWriter, in my case this was $qrCode.

Of course there will be things like logos that won't work as you can't convert bitmap to vector, but for a quick SVG solution it works perfectly fine!

The SVG also displays fine when just echo / printing it out, whereas the PNG needed to be base64_encoded as a data URI.

**Comment by endroid** [comment]
@Emilio-Staropoli you should use the setWriter() method to set your writer or instantiate the SvgWrtier yourself and use its writeString method.

**Comment by coffeduong** [comment]
1 more thing, set header `header('Content-Type: '.$svg->getContentType());` to help browser understand it's SVG image
