### ISSUE TITLE
error generating qr code

### ISSUE THREAD

**Issue by snowwolf007cn** [endroid/QrCode#28]
I got following error:
    PHP Notice:  Undefined offset: 15 in /var/www/html/qrservice/vendor/endroid/qrcode/src/Endroid/QrCode/QrCode.php on line 1183

PHP Version:
    PHP 5.5.23 (cli) (built: Mar 21 2015 22:04:59) 
    Copyright (c) 1997-2015 The PHP Group
    Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

**Comment by snowwolf007cn** [comment]
I found what cause the problem, the 'data' directory was skipped while I upload it to the server, it works now.

**Comment by endroid** [comment]
Ah ok
