### ISSUE TITLE
Cab be possible add a border to QR Codes ?

### ISSUE THREAD

**Issue by andrescevp** [endroid/QrCode#29]
Just these, because some times some app for read codes needs a border because the background can have colors that make interferences

thanks !

**Comment by quantumpacket** [comment]
Why don't you just use CSS to add a border to the QR code?

```html
<img src='images/qrcode.php' style='border: 5px solid COLOR'>
```

Where `COLOR` is a color that does not conflict with the current background.

**Comment by andrescevp** [comment]
Yes, I use it, but the issue is if you download the code you don't have the border.

**Comment by quantumpacket** [comment]
If the user is downloading the image, then you lose all control of what background color they will have it set against, and any border set will be as useful as setting no border.

**Comment by andrescevp** [comment]
Uffff I don't have any example ! but it's just a suggestion, if it's not possible no problem, the main is that the lib have a option to define a border in the image will can very nice !

**Comment by endroid** [comment]
Recently the setDrawBorder() method was added that allows you to add a border to the generated code.
