### ISSUE TITLE
how to solve char set problem

### ISSUE THREAD

**Issue by ofttryaj** [endroid/QrCode#34]
i want to show chinese label

**Comment by endroid** [comment]
Hi @ofttryaj please provide an example of a label you are trying to use and the result you are getting at the moment.

**Comment by ofttryaj** [comment]
@endroid 
$qrCode = new QrCode();
        $qrCode
            ->setText("http://www.baidu.com")
            ->setSize(150)
            ->setPadding(10)
            ->setErrorCorrection('high')
            ->setForegroundColor(array('r' => 0, 'g' => 0, 'b' => 0, 'a' => 0))
            ->setBackgroundColor(array('r' => 255, 'g' => 255, 'b' => 255, 'a' => 0))
            ->setLabel('这是一个搜索引擎')
            ->setLabelFontSize(12)
            ->render();

**Comment by ofttryaj** [comment]
![image](https://cloud.githubusercontent.com/assets/15887451/12575102/c861e01e-c444-11e5-89ed-42fc869e275e.png)

**Comment by ofttryaj** [comment]
@endroid 
When I set the label_font_path font, the font support Chinese, not garbled, thank you
![image](https://cloud.githubusercontent.com/assets/15887451/12575536/21440362-c448-11e5-8c4a-2e2ef2bf5bed.png)

**Comment by ofttryaj** [comment]
Hi @endroid  I want to add my logo in the two-dimensional code. how to do?

**Comment by endroid** [comment]
Hi @ofttryaj for now there is no support in the library for adding a logo as its main focus is generation of QR codes. This means you'll have to use some other library if you want to add one. GD and ImageMagick have some easy to use functions that allow you to watermark your generated QR code with with a logo. Good luck!

**Comment by endroid** [comment]
Nice to see you have the Chinese label working though!
