### ISSUE TITLE
The requested package endroid/qrcode could not be found in any version

### ISSUE THREAD

**Issue by wkii** [endroid/QrCode#42]
composer install:

try:

composer require "endroid/qrcode"
composer require endroid/qrcode:1.6.2
composer require "endroid/qrcode:dev-master" --prefer-dist
composer require "endroid/qrcode:dev-master" --prefer-source

-----------------
Problem 1
    - The requested package endroid/qrcode could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by endroid** [comment]
Hi @wkii when I create a clean composer file (via "composer init") and then require the library it is installed without any issues so nothing seems wrong with the library itself. I assume this is caused by a conflicting dependency or something else in your environment.
