### ISSUE TITLE
I can´t use this library . . . 

### ISSUE THREAD

**Issue by Kartomi16** [endroid/QrCode#45]
In Laravel 5.1 

I'm using the same code, but I can't get the image I'm get this code . . . And is NOT base64 code . . .  

�PNG  IHDR@Z���d!PLTE���������___???��ߟ���Ǧ�IDATx���;oA�aP�(���N1�L�HIZ��=N\.���8J$�P���H��+3��%�a��߯�b����+#֙!���|�X��� @���ٜ�ihR�M:�z @�������W�"�F� ��EnV* @����`�0g� @�p�@Sl~�J��[){ @��SD��O�d`� @�O����gu^�5]�5]�5]�g��]>���09�J�t�X @���Y�(W����7	@�p��},���Nl�� �# @�(V���c��L��r�  @�(S�b[V��z��@� ���GgK�J7�ȕ"]�5]�5]�5�}R�ĵ��d @�h����7T4$�d�1�Z @���KYigQh���f� @�w4U�,��W	@���М}��MX @�� h�q��2�e� @�hL��H6�E���@��B!��e��,�ۭu^��_�����K+8\`��_��^*59+t��T�-Wa�FO�o��i��_�T���,�֫����۲֖��7�U�G^�ͱR_;�nQ�fuy4��n0Sz�6߫v�+�WR�Z���5-�׃��UWzw�^��}���'#�Z��|~R�)Z� T�1��fA�]\�W�`]�A�8�Mث��1����q����l�/�v+�j씢s�����苴>���8�4��_]$G�E��*V#�t��4��w�`~�iF���T�ql��٫܇�,�7�����x=����Z�?��ɠ[���~��w>��_�P�䍷�v��-0��m�7����O�	�<��Qt&7τ\�IEND�B`�

**Comment by jkuchar** [comment]
that is actually png; you have set probably wrong http header

**Comment by netovs** [comment]
Use something like that: 
<img src="YouURL/qrcode/YourText" />

**Comment by abcsun** [comment]
add the content type as below
```
public function generateQrCode(Request $request)
    {
        header('Content-type: image/png');
        $qrCode = new QrCode();
        $qrCode
            ->setText('Life is too short to be generating QR codes')
            ->setSize(300)
            ->setPadding(10)
            ->setErrorCorrection('high')
            ->setForegroundColor(array('r' => 0, 'g' => 0, 'b' => 0, 'a' => 0))
            ->setBackgroundColor(array('r' => 255, 'g' => 255, 'b' => 255, 'a' => 0))
            ->setLabel('My label')
            ->setLabelFontSize(16)
            ->render();

    }
```

**Comment by Kartomi16** [comment]
I was added the "header('Content-type: image/png');" but looks like a broken image, still without deploy the QR Code . . .

**Comment by endroid** [comment]
Hi @Kartomi16. When I visit that URL I get the following error: "FatalErrorException in ImageController.php line 22: syntax error, unexpected '<<' (T_SL)" so at the moment something else seems wrong apart from the image issue you are mentioning.

If you get an invalid image maybe you could try to see if something else is accidentally written to the output during the request by using the ob_* calls just before and after generation. Another option is to let the same image data be written to a file using the $qrCode->save($filename) method. In case that results in a valid image something is clearly going wrong somewhere outside generation of the image.

Good luck finding the issue!

**Comment by Kartomi16** [comment]
@endroid Thanks for all you support. . .
