### ISSUE TITLE
Padding option omitted from getAvailableOptions() function

### ISSUE THREAD

**Issue by Szyp** [endroid/QrCode#46]
In QrCode/src/Factory/QrCodeFactory.php in getAvailableOptions() function, the 'padding' option is omitted.

This error was generate in Symphony when I use the padding option : An exception has been thrown during the rendering of a template ("The option "padding" does not exist. Defined options are: "background_color", "error_correction_level", "extension", "foreground_color", "label", "label_font_path", "label_font_size", "size", "text".")

**Comment by endroid** [comment]
Tnx for noticing. I fixed this in 1.7.2.

**Comment by deepakdhanji** [comment]
Any updates regarding this bug?

**Comment by endroid** [comment]
As I mentioned here this has been fixed. What version are you using? And if possible, I would upgrading to 2.x.
