### ISSUE TITLE
how to test the package ?

### ISSUE THREAD

**Issue by Jaggle** [endroid/QrCode#47]
now I'm using the symfony bundle you provided,now I want to have this bundle tested,I 'm not that familiar with phhunit,my command is:

```
 phpunit-5.3.4 -c vendor/endroid/qrcode  --bootstrap vendor/autoload.php vendor/endroid/qrcode/tests/
```
but it reports error like 'Error: Class 'Endroid\QrCode\QrCode' not found' and another two class not found error,what is the correct way to test a package ?

thank for you attention!

**Comment by endroid** [comment]
Hi @Jaggle you should execute the "composer install" and "phpunit" (without parameters) commands from the directory where the bundle is installed (vendor/endroid/qrcode-bundle) and not from the project or qrcode library directory.

In other words: go to vendor/endroid/qrcode-bundle, install all dependencies for the bundle using "composer install" and after that just run phpunit without any command line parameters.

**Comment by Jaggle** [comment]
thank you so much ! got new skill
