### ISSUE TITLE
Chinese garbled

### ISSUE THREAD

**Issue by shenmadouyaowen** [endroid/QrCode#51]
Hello, when I set when Chinese is garbled, I do not know how to solve? Thank you!

**Comment by scfff** [comment]
是因为调用的字体不支持中文， endroid\qrcode\src\QrCode.php 文件
        $this->setLabelFontPath(__DIR__.'/../assets/font/opensans.ttf');
改为中文字体路径即可。

**Comment by shenmadouyaowen** [comment]
`
$qrCode =new \Endroid\QrCode\QrCode();
    	$qrCode
    	->setText('http://www.test.com/')
    	->setSize(300)
    	->setPadding(10)
    	->setErrorCorrection('high')
    	->setForegroundColor(array('r' => 0, 'g' => 0, 'b' => 0, 'a' => 0))
    	->setBackgroundColor(array('r' => 255, 'g' => 255, 'b' => 255, 'a' => 0))
    	->setLabel('测试中文')
    	->setLabelFontPath(__DIR__.'/../assets/font/opensans.ttf')
    	->setLabelFontSize(16)
    	->setImageType(\Endroid\QrCode\QrCode::IMAGE_TYPE_PNG)
    	;
    	//$list = $Model->where($map)->paginate(5,false,['query' => $this->request->param(),]);
    	// now we can directly output the qrcode
    	header('Content-Type: '.$qrCode->getContentType());
    	$qrCode->render();
`
我之前试过,但只显示二维码,中文处什么都没有

**Comment by endroid** [comment]
Hi @shenmadouyaowen, I don't exacly know how the imagettftext function which is used here handles fonts, but it indeed looks like you need another font, as @scfff already mentioned. For example, when I use the font "Noto Sans CJK SC" from the URL https://www.google.com/get/noto/, the label is generated correctly.

**Comment by shenmadouyaowen** [comment]
@endroid Thank you for the link, I found I needed fonts, but it still does not display or garbled

**Comment by endroid** [comment]
Too bad. If you attach the font file you are using I can try to see if it works on my side. You can also create a simple script that only calls the imagettftext function with your font to see if this issue has any relation with my library.

**Comment by shenmadouyaowen** [comment]
@endroid  Thank you very much, according to the link you provided, I have found can display Chinese fonts.

**Comment by childeYin** [comment]
'Noto Sans CJK SC ' resolved my question ,  Chinese fonts can display, thanks.
