### ISSUE TITLE
URL-type QR codes

### ISSUE THREAD

**Issue by d2cs** [endroid/QrCode#53]
at this moment all qr codes are generated as TXT-type,
which prevents them from accessing URLS through scanning
in SOME popular scanning software, as TXT-type QR
is treated as simple text string not an URL.
yes, there is a difference between them.

**Comment by endroid** [comment]
Hi @d2cs thank you for your input. That would indeed be a nice addition. I labeled your question as enhancement.

**Comment by Laurent3170** [comment]
Hi, I think it's not an issue (or maybe I don't understand well the question), just add "http://" to the encoded text and it works. I use it for my shortcut website http://run.as

**Comment by endroid** [comment]
Hi @Laurent3170 I think you are right. I did some searching and could not find any QR code "type" in the specification. There are however some conventions on how specific data should be formatted (see https://github.com/zxing/zxing/wiki/Barcode-Contents) but these are all passed as plain text and I could not find a standard for specifying that an URL should be opened immediately after scanning.

@d2cs Could you please provide the following QR codes to illustrate the issue: one of the URL-type and one of the TEXT-type (and both containing an URL) where the first opens the URL automatically and the other doesn't. Please also mention the reader you use so I can verify we have a valid case.

**Comment by makoru-hikage** [comment]
A simple regex to the input string perhaps.

**Comment by fahmilatib** [comment]
@d2cs nice suggestion indeed
