### ISSUE TITLE
qrcode unicode compatible

### ISSUE THREAD

**Issue by lookwi** [endroid/QrCode#58]
I can't use UTF-8 for Chinese
Could you fix it ?
tks ,i'm waiting for you 
You jump, I jump!
tks again

**Comment by endroid** [comment]
Hi @lookwi I'm not sure I can help you. Can you post your code so I can try and reproduce the issue?

**Comment by lookwi** [comment]
use Endroid\QrCode\QrCode;

$qrCode = new QrCode();
$qrCode
    ->setText('Life is too short to be generating QR codes')
    ->setSize(300)
    ->setPadding(10)
    ->setErrorCorrection('high')
    ->setForegroundColor(array('r' => 0, 'g' => 0, 'b' => 0, 'a' => 0))
    ->setBackgroundColor(array('r' => 255, 'g' => 255, 'b' => 255, 'a' => 0))
    ->setLabel('你好世界！（Hello World）')
    ->setLabelFontSize(16)
    ->setImageType(QrCode::IMAGE_TYPE_PNG)
;

// now we can directly output the qrcode
header('Content-Type: '.$qrCode->getContentType());
$qrCode->render();


show image label 你好世界！（Hello World）error messy code Can't show Chinese
I guess the problem may be not compatible unicode

**Comment by endroid** [comment]
Hi @lookwi I was able to reproduce your issue and it looks like the font you are using does not contain the required characters. When I set a custom font as described in https://github.com/endroid/QrCode/issues/51 the issue seems resolved. Have you already tried that?
