### ISSUE TITLE
Using this without Composer

### ISSUE THREAD

**Issue by GiantKiwi** [endroid/QrCode#62]
I'm sure i'm not the only one wanting this - could you include instructions in the readme for utilisation without Composer? 

Deeply dislike dependency managers, but would like to use this, but it's not entirely clear on what I should be linking in my require statement.

**Comment by endroid** [comment]
Thank you for your question. The library is PSR-4 compliant so you should be able to autoload its classes like any other PSR-4 compliant library.

You can find an example here.
http://www.php-fig.org/psr/psr-4/examples/
