### ISSUE TITLE
Please fix usage example

### ISSUE THREAD

**Issue by stccorp** [endroid/QrCode#63]
could you please add require 'vendor/autoload.php'; to your example.   Without it, it will not work.

**Comment by endroid** [comment]
Hi @stccorp I try to keep code fragments concise. However I think you have a point that the readme could give some more information about autoloading classes so I added a note about using the autoloader in the installation section and removed the <?php tag to make clearer that the example is just a code fragment and not necessarily a complete working application.

Thank you for your input.
