### ISSUE TITLE
Missing display

### ISSUE THREAD

**Issue by Nelife** [endroid/QrCode#64]
Hi!
Can you help me fix missing display?
I use Vietnamese for label!
![t](https://cloud.githubusercontent.com/assets/12018657/20936305/b9a306e8-bc14-11e6-909e-ee861e73638f.png)

(Quét mã)
thank you so much!

**Comment by endroid** [comment]
Hi @Nelife what exactly do you mean by "missing display"? Please provide your code and attach the font you are using so I can try to reproduce the issue.

**Comment by Nelife** [comment]
Hi @endroid 
I use font default
IMG https://api.huongda.com/qrcode?ltxt=T%C3%B4i%20l%C3%A0%20Ngh%E1%BB%8B
And text: "Tôi là Nghị"

**Comment by endroid** [comment]
Hi @Nelife unfortunately I am not able to reproduce the issue you are having. When I set the label I get the following output with the current version of the library and the default font.
![qr_code](https://cloud.githubusercontent.com/assets/537253/22182940/15f11ebe-e0b2-11e6-98b0-7546c0dd7f89.png)
