### ISSUE TITLE
Let the logo have different image types

### ISSUE THREAD

**Issue by he426100** [endroid/QrCode#69]
`$image_info = getimagesize ( $this->logo );
            if ($image_info !== false) {
                $image_type = strtolower ( substr ( image_type_to_extension ( $image_info [2] ), 1 ) );
                $logo_image = call_user_func('imagecreatefrom'.$image_type, $this->logo);
            } else {
                $logo_image = call_user_func('imagecreatefrom'.$this->image_type, $this->logo);
            }`

**Comment by endroid** [comment]
Hi @he426100. There is no requirement on the image type of the logo. What are you trying to accomplish?

**Comment by he426100** [comment]
I want to provide an interface on the Internet, people just need to write content and LOGO  in the address bar to get a qrcode, such as " http://www.example.com/api/qr/?text=content&logo=http://www.example.com/logo.png "

**Comment by endroid** [comment]
Clear, thank you. I will look at it as soon as I have time. Or you could create a PR for me to merge.
