### ISSUE TITLE
Hide content of the QRcode 

### ISSUE THREAD

**Issue by coolbeatz71** [endroid/QrCode#73]
Hello man, how can we hide of the Qrcode so that another application can't print it? I am building an application for aunthentication using your library to store user information, but I dont want other application  to see the content when they scan it??

**Comment by cmcintosh** [comment]
QR code is plain text, it would the same as writing your social security number, name, and dob on a name tag and walking around town and hoping people cant read english.

**Comment by cmcintosh** [comment]
the other way to do it would be to take the user name / password and hash it, then use that to print the qr code.

**Comment by coolbeatz71** [comment]
Thanks cmcitosh! Yeah, this is what I did, but if another person create his own qrcode and store the hash value of my qrcode, he will access!! so i want to  avoid this  problem

**Comment by cmcintosh** [comment]
Um its highly unlikely, just use a really just use a salted hash and pick a high bit rate. http://softwareengineering.stackexchange.com/questions/49550/which-hashing-algorithm-is-best-for-uniqueness-and-speed

**Comment by coolbeatz71** [comment]
So how salted hash can avoid this? explain me please

**Comment by cmcintosh** [comment]
IT would not 100% prevent it, but if you hash the user's email, 
username, unique id, and then some random bit like a timestamp or 
something it decreases the chance.   I would suggest reading a bit more 
on the web on how salted hashes work.

**Comment by coolbeatz71** [comment]
Thanks you my friend
