### ISSUE TITLE
Could not generate

### ISSUE THREAD

**Issue by miku-sama** [endroid/QrCode#76]
Problem solving
I header in front of the problem with the addition of ob_clean();
![vhvuxb 0kxm o0f x0 0](https://cloud.githubusercontent.com/assets/25564950/24025793/abb6da8c-0af7-11e7-9cf0-5bfaf65841d5.png)

**Comment by endroid** [comment]
Hi @miku-sama please post the exact error message you are getting or a screenshot of it.

**Comment by miku-sama** [comment]
I didn't get an error
The resulting image cannot be displayed (the white box on the left is the generated QR code)

**Comment by miku-sama** [comment]
@endroid
I didn't get an error
The resulting image cannot be displayed (the white box on the left is the generated QR code)
I also tried the JPEG format can not be generated

**Comment by miku-sama** [comment]
![image](https://cloud.githubusercontent.com/assets/25564950/24030426/e74881de-0b17-11e7-831c-ee6efee37adf.png)
look it

**Comment by miku-sama** [comment]
Problem solving
I header in front of the problem with the addition of ob_clean();
