### ISSUE TITLE
Composer Installation Failed

### ISSUE THREAD

**Issue by alexkuang2016** [endroid/QrCode#78]
After inputing `composer require endroid/qrcode`
I got the following error feedback.
```
Using version ^1.9 for endroid/qrcode
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package endroid/qrcode No version set (parsed as 1.0.0) is satisfiable by endroid/qrcode[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.
```

**Comment by endroid** [comment]
Hi @alexkuang2016 unfortunately I am not able to reproduce the issue you're having. Here the library installs without problems and I do not see from here why it would not work.

Please try composer clear-cache, make sure you do not have the endroid/qrcode package in your composer.json or lock file prior to the require command. If that does not help please check if it works if you create a clean / empty composer.json (use composer init) and then require the library. Please report back if you have any further findings or if you have any information that enables us to reproduce the issue.

**Comment by alexkuang2016** [comment]
thanks a lot

**Comment by alexkuang2016** [comment]
after `composer init`:
```
The Process class relies on proc_open, which is not available on your PHP installation.
```

**Comment by alexkuang2016** [comment]
Then I delete `proc_open` from a list of `disabled_functions` in `php.ini` and new error occurs:
```
PHP Warning:  proc_get_status() has been disabled for security reasons in phar:///usr/local/bin/composer/vendor/symfony/process/Process.php on line 1283

Warning: proc_get_status() has been disabled for security reasons in phar:///usr/local/bin/composer/vendor/symfony/process/Process.php on line 1283
```
Now I've no idea what's next...

**Comment by alexkuang2016** [comment]
@endroid

**Comment by endroid** [comment]
Me neither, unfortunately. Composer inner workings and process / security are not really my field of expertise ;) Just to check if it has anything to do with my library: does composer install dependencies correctly for other projects? If not you'd better search in that direction.
