### ISSUE TITLE
Ability to add custom string around the QR Code

### ISSUE THREAD

**Issue by temuri416** [endroid/QrCode#79]
Hi,

First of all, thank you for your efforts!

Would it be possible to have a method that would add a (short) user-provided string around the generated QR code - above, below and on both sides (rotated 90 and 270 degrees) - centered relative to QR Code's dimensions?

Cheers!

**Comment by endroid** [comment]
Hi @temuri416 this is not something I will build myself at the moment but if someone can contribute and finds an elegant solution so that it does not have a negative impact on the current code base I have no problems merging this feature.
