### ISSUE TITLE
Example usage is outdated for 2.0.2

### ISSUE THREAD

**Issue by Rotzbua** [endroid/QrCode#80]
For version 2.0.2 the usage do not work. Functions do not exist or not invokable.

## Problems

Function do not exist:

    ->setLabelFontSize(16)
    ->setImageType(QrCode::IMAGE_TYPE_PNG)

Function do not invoke:

    ->setErrorCorrectionLevel('H')
    ->setLabel('Scan the code')

## Complete code

```php
use Endroid\QrCode\QrCode;

$qrCode = new QrCode();
$qrCode
    ->setText('Life is too short to be generating QR codes')
    ->setSize(300)
    ->setQuietZone(2)
    ->setErrorCorrectionLevel('H')
    ->setForegroundColor(['r' => 0, 'g' => 0, 'b' => 0, 'a' => 0])
    ->setBackgroundColor(['r' => 255, 'g' => 255, 'b' => 255, 'a' => 0])
    ->setLabel('Scan the code')
    ->setLabelFontSize(16)
    ->setImageType(QrCode::IMAGE_TYPE_PNG)
;

// now we can directly output the qrcode
header('Content-Type: '.$qrCode->getContentType());
$qrCode->render();

// save it to a file
$qrCode->save('qrcode.png');

// or create a response object
$response = new Response($qrCode->get(), 200, ['Content-Type' => $qrCode->getContentType()]);
```

**Comment by childeYin** [comment]
I have this problem too

**Comment by endroid** [comment]
You're right. I'm working on 2.x at the moment and will port existing functionality within a few days (that's why I did not update all of documentation). Please use 1.x if you need any of the label or logo functionality now.

**Comment by endroid** [comment]
I decided to remove the tags from the 2.x branch as the version is not stable yet (I accidentally tagged it) and completion of this version will take some longer than a few days. Please use a stable version from the 1.x branch in the meanwhile.

**Comment by Rotzbua** [comment]
@endroid I use 1.x, works fine, thanks for your work. Informational: I tested 2.0.2 with removing all function from the example which do not work. Then it generates a qrcode but my scanner could not read it.
