### ISSUE TITLE
UndefinedMethodException in QrCodeExtension.php line 69: Attempted to call an undefined method named "getData" of class "Endroid\QrCode\QrCode".

### ISSUE THREAD

**Issue by dahomz** [endroid/QrCode#81]
Hi, great bundle easy to use with good docs.

In version 2.02 when calling the uri from a twig template i.e

`<img src="{{ qrcode_data_uri(message, { size: 150 }) }}" />`

receiving the following error

```
UndefinedMethodException in QrCodeExtension.php line 69:
Attempted to call an undefined method named "getData" of class "Endroid\QrCode\QrCode".
```

Seems to be fixed with a small modification to the qrcodeDataUriFunction

`return $qrCode->getPngDataUri();`

**Comment by endroid** [comment]
Hi @dahomz I accidentally tagged version 2.x while this version is not stable yet and should not be used. So please use a stable version from the 1.x branch for now. I removed the tags and will add new tags as soon as I think the new version is stable.
