### ISSUE TITLE
 Warning: constant(): Couldn't find constant Endroid\QrCode\QrCode::LEVEL_

### ISSUE THREAD

**Issue by linxlad** [endroid/QrCode#83]
Getting the following warning.

Warning: constant(): Couldn't find constant Endroid\QrCode\QrCode::LEVEL_ in Endroid\QrCode\QrCode->setErrorCorrection() (line 243 of vendor/endroid/qrcode/src/QrCode.php).

**Comment by endroid** [comment]
Hi @linxlad please post your version and code so I can see if I can reproduce the issue.

**Comment by endroid** [comment]
Hi @linxlad this is caused by to the other issue you posted. The constant is not correctly resolved because of the failing strtoupper. Please provide the code in the other ticket, maybe I can help.
