### ISSUE TITLE
Error on constant BC break php < 5.6.0

### ISSUE THREAD

**Issue by benschumi** [endroid/QrCode#84]
Parse error: syntax error, unexpected '.', expecting ',' or ';' in endroid/qrcode/src/QrCode.php on line 23

`const DEFAULT_FONT_PATH = __DIR__ . '/../font/open_sans.ttf';`

I'm in php 5.5.9
Constant expression support was added in PHP 5.6.0.

**Comment by endroid** [comment]
Hi @benschumi version 2.x is still not stable although I accidentally tagged it so please use a stable version of the 1.x branch. I removed the tags and updated the minimum requirement. Upon release I will decide on the minimum requirements of the 2.x branch.
