### ISSUE TITLE
Twig Extension

### ISSUE THREAD

**Issue by ljfio** [endroid/QrCode#85]
I'm having an issue using the Twig Extension within Slim without having to add `symfony/dependency-injection` as a dependency in my composer.json

Is this missing from your dependency list or am I missing something?

````
PHP Fatal error:  Trait 'Symfony\Component\DependencyInjection\ContainerAwareTrait' not found in vendor/endroid/qrcode/src/Bundle/Twig/Extension/QrCodeExtension.php on line 21

Fatal error: Trait 'Symfony\Component\DependencyInjection\ContainerAwareTrait' not found in vendor/endroid/qrcode/src/Bundle/Twig/Extension/QrCodeExtension.php on line 21
````

**Comment by endroid** [comment]
Yes, looks like it is missing. Maybe it is possible to change the extension so it directly injects the desired services instead of the container itself..

**Comment by endroid** [comment]
FYI: I made sure the twig extension in 2.x will not be dependent on the service container. You can try that version as soon as it is released.
