### ISSUE TITLE
Response class not found

### ISSUE THREAD

**Issue by anujsharma9196** [endroid/QrCode#88]
Crating a response in CakePHP 3.4 application gives error

`Class Response not found`

```
use App\Controller\AppController;
use Endroid\QrCode\ErrorCorrectionLevel;
use Endroid\QrCode\LabelAlignment;
use Endroid\QrCode\QrCode;
use Endroid\QrCode\Writer\PngWriter;
use Endroid\QrCode\Writer\SvgWriter;

$qrCode = new QrCode('Hello World');
$qrCode
       ->setSize(300)
       ->setImageType(QrCode::IMAGE_TYPE_PNG);

// Create a response object
$response = new \Response(
        $qrCode->writeString(PngWriter::class),
        Response::HTTP_OK,
        ['Content-Type' => $qrCode->getContentType(PngWriter::class)]);
```

Removing **`\`** from **`new \Response`** gives

` Call to undefined method Endroid\QrCode\QrCode::writeString() `

**Comment by endroid** [comment]
Hi @anujsharma9196 in the example I meant a symfony http-foundation response but you are free to put the resulting string in any type of response or output it directly, whatever you like.

I updated the example to include the missing use statement.

**Comment by anujsharma9196** [comment]
why it is showing error as 
` Call to undefined method Endroid\QrCode\QrCode::writeString() `
on 
```
$response = $this->response;
$response = $response->withType($qrCode->getContentType(PngWriter::class))
     ->withStringBody($qrCode->writeString(PngWriter::class));
```

**Comment by lem356** [comment]
Hi @anujsharma9196 and endroid. I'm having the same problem with cakePHP2.x  and I'm not able to solve it (i've lost 2 days).   I was wondering if the folders structure I get once I do the installation it's correct or not. I've tryed to put my composer,json directly in /app/vendor   and putting it in a subfolder structure (app/vendor/Endroid/QrCode) with no result. Could you please tell me what i'm doing wrong?
Thank you very much in advance.
Regards, 
Leah.

**Comment by endroid** [comment]
Hi @lem356 I don't use cakePHP myself but your composer.json should always be in your project root. The vendor folder will be created by composer automatically and should not contain any user generated files. Using composer should be as easy as creating a composer.json (or generating one via "composer init"), including the library via "composer require endroid/qrcode" and requiring the generated vendor/autoload.php in your script.

Hope this helps. If not, please consult the cakePHP or Composer community as this is somewhat out of the scope of this specific library (no offense).
