### ISSUE TITLE
Call to undefined method Endroid\QrCode\QrCode::writeString()

### ISSUE THREAD

**Issue by anujsharma9196** [endroid/QrCode#90]
why it is showing error as 
` Call to undefined method Endroid\QrCode\QrCode::writeString() `
on 
```
$response = $this->response;
$response = $response->withType($qrCode->getContentType(PngWriter::class))
     ->withStringBody($qrCode->writeString(PngWriter::class));
```

**Comment by endroid** [comment]
Hi @anujsharma9196 what version are you using? In version 2.0.2 see in the code that the QrCode class does have a writeString method (see https://github.com/endroid/QrCode/blob/master/src/QrCode.php#L500). Could you check that you also have the method defined in your class at line 500?

If not, please upgrade to the correct version. If it is on line 500, please check the following.
1. The output you get when you echo PngWriter::class
2. The output of $qrCode->getContentType(PngWriter::class)
3. Output all class methods using reflection and post them here

$reflectionClass = new \ReflectionClass($qrCode);
$methods = $reflectionClass->getMethods();
foreach ($methods as $method) {
    echo $method->getName().'<br />';
}

That should give some more information.

**Comment by anujsharma9196** [comment]
Yes, it was 1.9.*, updated to 2.0.* and working now
Thanks
