### ISSUE TITLE
Twig issue with Validation reader

### ISSUE THREAD

**Issue by ThomasLandauer** [endroid/QrCode#93]
When I do (taken from https://github.com/endroid/QrCode#twig-extension):
````
<img src="{{ qrcode_data_uri(message, { size: 150 }) }}" />
````
... I get:  
````
An exception has been thrown during the rendering of a template ("Validation reader read "" instead of "lorem ipsum"").
````
I have twig/twig 2.3.2 with Symfony 2.8.19.

**Comment by endroid** [comment]
I updated the exception message so it is more descriptive. If you want to use validation and think the qr code should be readable, please create a failing test case in tests/QrCodeTest.php so I can see if it's something in the library or in one of the dependencies.

**Comment by ThomasLandauer** [comment]
You can't reproduce?  
When I do
```
<img src="{{ qrcode_data_uri('lorem ipsum', { size: 150 }) }}" />
````
or
````
<img src="{{ qrcode_data_uri('lorem ipsum') }}" />
````
I now get (v2.0.5):
````
An exception has been thrown during the rendering of a template ("Warning: strlen() expects parameter 1 to be string, array given")
````
...with a reference to `vendor\bacon\bacon-qr-code\src\BaconQrCode\Writer.php at line 78`:
````
if (strlen($content) === 0) {
````

**Comment by ThomasLandauer** [comment]
Fixed with https://github.com/endroid/QrCode/pull/99
